name: mezgebe_sbhat_java
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  provider: ^6.1.2
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  path: ^1.9.0
  retry: ^3.1.2
  flutter_slidable: ^3.1.1
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.1
  just_audio: ^0.9.46
  syncfusion_flutter_pdfviewer: ^29.1.37
  # flutter_sound: ^9.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/
    - assets/images/
